AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GIG Economy !! This my first CICD Deployment.
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs8.10
    Timeout: 5
Resources:
  eventLogging:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CICDLoggingLambda
      Handler: eventLogging.handler
      Timeout: 3
      Events:
        GetLogger:
          Type: Api
          Properties:
            Path: /v1/logging
            Method: get
      CodeUri: s3://hv-gig-economy-sam-cicd-demo1/efcaae0248a36fcc292e1111af13a9ae
  concatenateString:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CICDConcatenateLambda
      Handler: concatenateString.handler
      Events:
        PostConcat:
          Type: Api
          Properties:
            Path: /v1/concatenate
            Method: post
      CodeUri: s3://hv-gig-economy-sam-cicd-demo1/efcaae0248a36fcc292e1111af13a9ae
